version: '3'
services:
  mcp-ping:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-ping.rule=Host(`mcp-ping.stuartmason.co.uk`)"
      - "traefik.http.services.mcp-ping.loadbalancer.server.port=3001"
      - "traefik.http.routers.mcp-ping.entrypoints=https"
      - "traefik.http.routers.mcp-ping.tls=true"
      - "traefik.http.routers.mcp-ping.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.mcp-ping.middlewares=gzip"
